name: Android APK Build

on:
  push:
    branches:
      - master  # 当代码推送到 main 分支时触发
  pull_request:
    branches:
      - master  # 允许在 PR 时触发

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest  # 使用 Ubuntu 作为运行环境

    steps:
      # **1. 检出代码**
      - name: Checkout Repository
        uses: actions/checkout@v4

      # **2. 设置 JDK（Android 构建需要 Java 环境）**
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # 适用于 Android Gradle Plugin 8.x+

      # **3. 设置 Gradle 缓存（加速构建）**
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # **4. 运行 Gradle 构建 APK**
      - name: Build APK
        run: ./gradlew assembleDebug

      # **5. 上传 APK 作为构建产物**
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

